# Generated by Django 4.0.6 on 2022-10-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
    ]
